### ISSUE TITLE
java.lang.NoSuchMethodError: io.reactivex.Single.ignoreElement()Lio/reactivex/Completable; 

### ISSUE THREAD

**Issue by kanedafromparis** [FroMage/redpipe#45]
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions prior to 1.8.
SLF4J: Ignoring binding found at [jar:file:/Users/csabourdin/.m2/repository/org/slf4j/slf4j-jdk14/1.6.3/slf4j-jdk14-1.6.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#ignoredBindings for an explanation.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/Users/csabourdin/.m2/repository/io/netty/netty-common/4.1.19.Final/netty-common-4.1.19.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Aug 03, 2018 11:42:17 AM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 5.4.1.Final
Aug 03, 2018 11:42:17 AM org.jboss.resteasy.plugins.validation.AbstractValidatorContextResolver getValidatorFactory
INFO: RESTEASY008550: Unable to find CDI supporting ValidatorFactory. Using default ValidatorFactory
MLog initialization issue: slf4j found no binding or threatened to use its (dangerously silent) NOPLogger. We consider the slf4j library not found.
Aug 03, 2018 11:42:18 AM com.mchange.v2.log.MLog 
INFO: MLog clients using java 1.4+ standard logging.
Aug 03, 2018 11:42:18 AM com.mchange.v2.c3p0.C3P0Registry 
INFO: Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
Exception in thread "main" java.lang.NoSuchMethodError: io.reactivex.Single.ignoreElement()Lio/reactivex/Completable;
	at net.redpipe.engine.core.Server.lambda$null$15(Server.java:248)
	at io.reactivex.internal.operators.completable.CompletableDefer.subscribeActual(CompletableDefer.java:36)
	at io.reactivex.Completable.subscribe(Completable.java:1794)
	at net.redpipe.engine.rxjava2.ContextPropagatorOnCompletableAssemblyAction$ContextPropagatorCompletable.subscribeActual(ContextPropagatorOnCompletableAssemblyAction.java:36)
	at io.reactivex.Completable.subscribe(Completable.java:1794)
	at io.reactivex.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.next(CompletableConcatArray.java:89)
	at io.reactivex.internal.operators.completable.CompletableConcatArray.subscribeActual(CompletableConcatArray.java:33)
	at io.reactivex.Completable.subscribe(Completable.java:1794)
	at net.redpipe.engine.rxjava2.ContextPropagatorOnCompletableAssemblyAction$ContextPropagatorCompletable.subscribeActual(ContextPropagatorOnCompletableAssemblyAction.java:36)
	at io.reactivex.Completable.subscribe(Completable.java:1794)
	at io.reactivex.internal.operators.completable.CompletableDefer.subscribeActual(CompletableDefer.java:43)
	at io.reactivex.Completable.subscribe(Completable.java:1794)
	at net.redpipe.engine.rxjava2.ContextPropagatorOnCompletableAssemblyAction$ContextPropagatorCompletable.subscribeActual(ContextPropagatorOnCompletableAssemblyAction.java:36)
	at io.reactivex.Completable.subscribe(Completable.java:1794)
	at io.reactivex.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.next(CompletableConcatArray.java:89)
	at io.reactivex.internal.operators.completable.CompletableConcatArray.subscribeActual(CompletableConcatArray.java:33)
	at io.reactivex.Completable.subscribe(Completable.java:1794)
	at net.redpipe.engine.rxjava2.ContextPropagatorOnCompletableAssemblyAction$ContextPropagatorCompletable.subscribeActual(ContextPropagatorOnCompletableAssemblyAction.java:36)
	at io.reactivex.Completable.subscribe(Completable.java:1794)
	at io.reactivex.internal.operators.completable.CompletableDefer.subscribeActual(CompletableDefer.java:43)
	at io.reactivex.Completable.subscribe(Completable.java:1794)
	at net.redpipe.engine.rxjava2.ContextPropagatorOnCompletableAssemblyAction$ContextPropagatorCompletable.subscribeActual(ContextPropagatorOnCompletableAssemblyAction.java:36)
	at io.reactivex.Completable.subscribe(Completable.java:1794)
	at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onSuccess(SingleFlatMapCompletable.java:91)
	at io.reactivex.internal.observers.ResumeSingleObserver.onSuccess(ResumeSingleObserver.java:46)
	at net.redpipe.engine.rxjava2.ContextPropagatorOnSingleCreateAction$ContextCapturerSingle.onSuccess(ContextPropagatorOnSingleCreateAction.java:61)
	at net.redpipe.engine.rxjava2.ContextPropagatorOnSingleCreateAction$ContextCapturerSingle.onSuccess(ContextPropagatorOnSingleCreateAction.java:61)
	at net.redpipe.engine.rxjava2.ContextPropagatorOnSingleCreateAction$ContextCapturerSingle.onSuccess(ContextPropagatorOnSingleCreateAction.java:61)
	at io.reactivex.internal.operators.single.SingleDoOnError$DoOnError.onSuccess(SingleDoOnError.java:52)
	at net.redpipe.engine.rxjava2.ContextPropagatorOnSingleCreateAction$ContextCapturerSingle.onSuccess(ContextPropagatorOnSingleCreateAction.java:61)
	at net.redpipe.engine.rxjava2.ContextPropagatorOnSingleCreateAction$ContextCapturerSingle.onSuccess(ContextPropagatorOnSingleCreateAction.java:61)
	at io.reactivex.internal.operators.completable.CompletableToSingle$ToSingle.onComplete(CompletableToSingle.java:68)
	at net.redpipe.engine.rxjava2.ContextPropagatorOnCompletableCreateAction$ContextCapturerCompletable.onComplete(ContextPropagatorOnCompletableCreateAction.java:62)
	at net.redpipe.engine.rxjava2.ContextPropagatorOnCompletableCreateAction$ContextCapturerCompletable.onComplete(ContextPropagatorOnCompletableCreateAction.java:62)
	at net.redpipe.engine.rxjava2.ContextPropagatorOnCompletableCreateAction$ContextCapturerCompletable.onComplete(ContextPropagatorOnCompletableCreateAction.java:62)
	at net.redpipe.engine.rxjava2.ContextPropagatorOnCompletableCreateAction$ContextCapturerCompletable.onComplete(ContextPropagatorOnCompletableCreateAction.java:62)
	at io.reactivex.internal.disposables.EmptyDisposable.complete(EmptyDisposable.java:68)
	at io.reactivex.internal.operators.completable.CompletableEmpty.subscribeActual(CompletableEmpty.java:27)
	at io.reactivex.Completable.subscribe(Completable.java:1794)

**Comment by kanedafromparis** [comment]
I was able to make it works by setting rxjava to 2.2.0 version. 
I am not sur that the best solution but it works on my machine ;-)

```
        <dependency>
            <groupId>io.reactivex.rxjava2</groupId>
            <artifactId>rxjava</artifactId>
            <version>2.2.0</version>
        </dependency>
```

**Comment by kanedafromparis** [comment]
Great, thanks you.

And thank you for this project seems very, very promising.

Le lun. 6 août 2018 à 15:18, Stéphane Épardaud <notifications@github.com> a
écrit :
